//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Core.Resources.Services.Auth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Core.Resources.Services.Auth.AuthService", typeof(AuthService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is already confirmed.
        /// </summary>
        public static string Email_Confirm_Already_Confirmed {
            get {
                return ResourceManager.GetString("Email_Confirm_Already-Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while confirming the email address.
        /// </summary>
        public static string Email_Confirm_Error {
            get {
                return ResourceManager.GetString("Email_Confirm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address&apos;s format is invalid.
        /// </summary>
        public static string Email_Format_Invalid {
            get {
                return ResourceManager.GetString("Email_Format_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect.
        /// </summary>
        public static string Password_SignIn_Password_Incorrect {
            get {
                return ResourceManager.GetString("Password_SignIn_Password-Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating the user. Please verify the password.
        /// </summary>
        public static string User_Create_Error {
            get {
                return ResourceManager.GetString("User_Create_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already exists.
        /// </summary>
        public static string User_Create_Exists {
            get {
                return ResourceManager.GetString("User_Create_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string User_Find_Not_Found {
            get {
                return ResourceManager.GetString("User_Find_Not-Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while signing in.
        /// </summary>
        public static string User_SignIn_Error {
            get {
                return ResourceManager.GetString("User_SignIn_Error", resourceCulture);
            }
        }
    }
}
